Repository chrisfalla/Frontend_La_Brujula_Llanera, pull requests merged in 2025-05, with the labels that each got.

#88 T-076-V2 Create component NavigationTopBar
  src/presentation/components/NavigationTopBar/NavigationTopBar.js
Labels: enhancement

#92 T-075-V2 modify the header component
  src/presentation/components/Header.js
  src/presentation/components/MainHeader/MainHeader.js
  src/presentation/screens/Categories/CategoriesScreen.js
  src/presentation/screens/Home/HomeScreen.js
  src/presentation/screens/Map/MapaScreen.js
  src/shared/assets/Avatar.png
Labels: enhancement

#94 T-078-V2 Create Detail Screen
  src/presentation/components/DetailPlaces/Gallery.js
  src/presentation/components/DetailPlaces/ImageMainDetail.js
  src/presentation/components/DetailPlaces/InfoDetail.js
  src/presentation/components/DetailPlaces/StarRating.js
  src/presentation/screens/Detail/DetailScreen.js
Labels: duplicate, help wanted

#95 T-050-V2 Create Categorie Screen
  src/presentation/components/Search/Search.js
  src/presentation/screens/Categories/CategoriesScreen.js
Labels: duplicate

#96 T-074-V2 Component MostVisitesPlaces
  src/presentation/components/MostVisitedPlaces/MostVisitedPlaces.js
Labels: duplicate

#97 T-071-V2 Create Component Horizontal card place
  src/presentation/components/HorizontalCardPLace/HorizontalCardPlace.js
Labels: bug, duplicate, help wanted

#110 T-109 Update Component MostVisitedPlaces
  src/presentation/components/MostVisitedPlaces/MostVisitedPlaces.js
Labels: duplicate

#112 T-106 Modify Components Global Style - Christofer
  src/presentation/components/CustomButton/CustomButton.js
  src/presentation/components/CustomCheap/CustomCheap.js
  src/presentation/components/CustomInput/CustomInputText.js
  src/presentation/components/Dashboard/Button.js
  src/presentation/components/Dashboard/Card.js
  src/presentation/components/Dashboard/ChartPlaceholder.js
  src/presentation/components/MainHeader/MainHeader.js
  src/presentation/components/Recovery/Status.js
  src/presentation/components/Recovery/Status1.js
  src/presentation/components/Recovery/Status2.js
  src/presentation/components/Recovery/Status3.js
  src/presentation/components/VerticalPlaceCard/VerticalPlaceCard.js
Labels: duplicate

#119 T-117 modify step component lógic
  src/presentation/components/Steper/CustomSteper.js
Labels: enhancement

#124 T-114 Backend implementation on Home Screen
  package-lock.json
  package.json
  src/data/datasources/categories/categoriesDataSource.js
  src/data/datasources/places/mostVisitedPlacesDataSources.js
  src/data/datasources/places/placesByTagsDataSource.js
  src/data/datasources/places/topRatedPlacesDataSource.js
  src/data/datasources/tags/tagsDataSource.js
  src/data/datasources/users/usersDataSource.js
  src/data/repositories/places/placesRepository.js
  src/data/repositories/tags/tagsRepository.js
  src/domain/models/.txt
  src/domain/models/categories/category.js
  src/domain/models/places/places.js
  src/domain/models/tags/Tag.js
  src/domain/usecases/.txt
  src/domain/usecases/categories/getCategoriesUseCase.js
  src/domain/usecases/places/getMostVisitedPlacesUseCase.js
  src/domain/usecases/places/getPlacesByTagsUseCase.js
  src/domain/usecases/places/getTopRatedPlacesByCategoryUseCase.js
  src/domain/usecases/tags/getDefaultTagsUseCase.js
  src/infraestructure/api/categories/categoriesApi.js
  src/infraestructure/services/navigationService.js
  src/infraestructure/storage/.txt
  src/infrastructure/api/categories/categoriesApi.js
  src/infrastructure/api/places/placesApi.js
  src/infrastructure/api/tags/tagsApi.js
  src/infrastructure/api/users/usersApi.js
  src/infrastructure/services/httpClientService.js
  src/infrastructure/services/navigationService.js
  src/infrastructure/storage/.txt
  src/infrastructure/storage/userStorage.js
  src/presentation/components/CategoryCardSmall/CategoryCardSmall.js
  src/presentation/components/CustomCheap/CustomCheap.js
  src/presentation/components/HorizontalCardPLace/HorizontalCardPlace.js
  src/presentation/components/MainHeader/MainHeader.js
  src/presentation/components/MostVisitedPlaces/MostVisitedPlaces.js
  src/presentation/components/Rating/Rating.js
  src/presentation/components/VerticalPlaceCard/VerticalPlaceCard.js
  src/presentation/hooks/.txt
  src/presentation/hooks/places/useMostVisitedPlaces.js
  src/presentation/hooks/places/usePlacesByTags.js
  src/presentation/hooks/places/useTopRatedPlacesByCategory.js
  src/presentation/hooks/tags/useTags.js
  src/presentation/navigation/AppNavigation.js
  src/presentation/screens/Home/HomeScreen.js
  src/presentation/screens/Register/RegisterStepOne/RegisterStepOneScreen.js
  src/presentation/screens/Register/RegisterStepTwo/RegisterStepTwoScreen.js
  src/react-native.config.js
  src/shared/store/categoriesSlice/categoriesSlice.js
  src/shared/store/placesByTagsSlice/placesByTagsSlice.js
  src/shared/store/store.js
  src/shared/store/topRatedPlacesSlice/topRatedPlacesSlice.js
  tsconfig.json
Labels: duplicate, enhancement

#140 T-129 Implementation UI Create SearchScreen
  src/presentation/components/NavigationTopBar/NavigationTopBar.js
  src/presentation/screens/Search/SearchScreen.js
Labels: enhancement

#142 T-121 create FavoritesScreen
  package-lock.json
  package.json
  src/data/datasources/favorites/favoritesDataSource.js
  src/data/repositories/favorites/favoritesRepository.js
  src/domain/models/favorites/favorite.js
  src/domain/usecases/favorites/getFavoritesUseCase.js
  src/infrastructure/api/favorites/favoritesApi.js
  src/presentation/components/NavigationTopBar/NavigationTopBar.js
  src/presentation/components/VerticalPlaceCard/VerticalPlaceCard.js
  src/presentation/hooks/favorites/useFavorites.js
  src/presentation/screens/Favorites/FavoritesScreen.js
  src/shared/store/favoritesSlice/favoritesSlice.js
  src/shared/store/store.js
Labels: enhancement

#144 T-126 Implementation UI Password Recovery
  src/presentation/components/CustomButton/CustomButton.js
  src/presentation/components/CustomInput/CustomInputText.js
  src/presentation/components/Steper/CustomSteper.js
  src/presentation/navigation/AppNavigation.js
  src/presentation/screens/Login/LoginScreen.js
  src/presentation/screens/PasswordRecovery/PasswordRecoveryStepOneScreen.js
  src/presentation/screens/PasswordRecovery/PasswordRecoveryStepThreeScreen.js
  src/presentation/screens/PasswordRecovery/PasswordRecoveryStepTwoScreen.js
Labels: duplicate, enhancement

#146 T-145 Update Component VerticalCardPLace in View Home
  src/presentation/screens/Home/HomeScreen.js
Labels: duplicate

#148 T-125 Implementation UI LoginScreen
  src/presentation/components/MainHeader/MainHeader.js
  src/presentation/components/NavigationTopBar/NavigationTopBar.js
  src/presentation/screens/Login/LoginScreen.js
  src/shared/assets/logoLeft.png
  src/shared/assets/logoRigth.png
Labels: enhancement

#150 logout sucesfully and return to view logiscreen
  src/infrastructure/services/navigationService.js
  src/presentation/navigation/AppNavigation.js
  src/presentation/screens/Profile/ProfileScreen.js
Labels: enhancement

#151 T-132 Implementation UI Component Dropdown
  package-lock.json
  package.json
  src/presentation/components/Dropdown/CustomDropdown.js
Labels: enhancement

#153 T-133 Integration Backend Login
  src/data/datasources/users/usersDataSource.js
  src/data/repositories/users/usersRepository.js
  src/domain/models/users/userLogin.js
  src/domain/usecases/user/loginUserUseCase.js
  src/infrastructure/api/users/usersApi.js
  src/presentation/screens/Login/LoginScreen.js
  src/presentation/screens/PasswordRecovery/PasswordRecoveryStepOneScreen.js
  src/presentation/screens/PasswordRecovery/PasswordRecoveryStepThreeScreen.js
  src/presentation/screens/PasswordRecovery/PasswordRecoveryStepTwoScreen.js
Labels: enhancement

#155 T-154 Change URL Backend
  src/shared/constants/environment/environment.js
Labels: bug, help wanted

#158 T-131 -Implementation UI Create ReviewsSCreen
  package-lock.json
  package.json
  src/data/datasources/users/usersDataSource.js
  src/data/repositories/users/usersRepository.js
  src/domain/models/users/userLogin.js
  src/domain/usecases/user/loginUserUseCase.js
  src/infrastructure/api/users/usersApi.js
  src/infrastructure/services/navigationService.js
  src/presentation/components/MainHeader/MainHeader.js
  src/presentation/components/NavigationTopBar/NavigationTopBar.js
  src/presentation/components/Rating/Rating.js
  src/presentation/components/ReviewCard/ReviewCard.js
  src/presentation/navigation/AppNavigation.js
  src/presentation/screens/Login/LoginScreen.js
  src/presentation/screens/PasswordRecovery/PasswordRecoveryStepOneScreen.js
  src/presentation/screens/PasswordRecovery/PasswordRecoveryStepThreeScreen.js
  src/presentation/screens/PasswordRecovery/PasswordRecoveryStepTwoScreen.js
  src/presentation/screens/Profile/ProfileScreen.js
  src/presentation/screens/Reviews/PlaceReviewsScreen.js
  src/shared/assets/logoLeft.png
  src/shared/assets/logoRigth.png
Labels: duplicate, enhancement

#163 T-134 Integration Backend Recovery Password
  src/data/datasources/users/usersDataSource.js
  src/data/repositories/users/usersRepository.js
  src/domain/models/passwordRecovery/passwordRecovery.js
  src/domain/usecases/passwordRecovery/getPasswordRecoveryUseCase.js
  src/infrastructure/api/users/usersApi.js
  src/presentation/navigation/AppNavigation.js
  src/presentation/screens/PasswordRecovery/PasswordRecoveryStepOneScreen.js
  src/presentation/screens/PasswordRecovery/PasswordRecoveryStepThreeScreen.js
  src/presentation/screens/PasswordRecovery/PasswordRecoveryStepTwoScreen.js
  src/presentation/screens/Places/.txt
  src/shared/constants/environment/environment.js
Labels: duplicate, enhancement

#169 T-164 Integration Backend Add and Delete Favorites
  src/data/repositories/favorites/favoritesRepository.js
  src/domain/models/favorites/favorite.js
  src/domain/usecases/favorites/addFavoriteUseCase.js
  src/domain/usecases/favorites/deleteFavoriteUseCase.js
  src/infrastructure/api/favorites/favoritesApi.js
  src/presentation/components/MainImage/MainImage.js
  src/presentation/components/NavigationTopBar/NavigationTopBar.js
  src/presentation/components/Rating/Rating.js
  src/presentation/components/VerticalPlaceCard/VerticalPlaceCard.js
  src/presentation/navigation/MainNavigator.js
  src/presentation/screens/Favorites/FavoritesScreen.js
  src/presentation/screens/Home/HomeScreen.js
  src/shared/constants/environment/environment.js
  src/shared/store/favoritesSlice/favoritesSlice.js
  src/shared/store/store.js
Labels: duplicate, enhancement

#170 T-168 modify SearchScreen
  src/data/datasources/places/placesByCategoryDataSource.js
  src/data/repositories/places/placesRepository.js
  src/domain/models/places/places.js
  src/domain/usecases/places/getPlacesByCategoryUseCase.js
  src/infrastructure/api/places/placesApi.js
  src/presentation/navigation/AppNavigation.js
  src/presentation/navigation/MainNavigator.js
  src/presentation/screens/Categories/CategoriesScreen.js
  src/presentation/screens/Home/HomeScreen.js
  src/presentation/screens/Search/SearchScreen.js
Labels: enhancement

#173 T-165 Integrartion Backend InformationScreen
  src/data/datasources/users/usersDataSource.js
  src/data/repositories/users/usersRepository.js
  src/domain/usecases/user/updateUserUseCase.js
  src/infrastructure/api/users/usersApi.js
  src/presentation/components/MainHeader/MainHeader.js
  src/presentation/screens/Profile/ProfileScreen.js
  src/presentation/screens/ProfileInformation/ProfileInformationScreen.js
  src/shared/store/authSlice/authSlice.js
Labels: enhancement
