Repository chrisfalla/Frontend_La_Brujula_Llanera, pull requests merged in 2025-06, with the labels that each got.

#175 T - 166 Create Screen Terms and Condition
  src/presentation/navigation/AppNavigation.js
  src/presentation/screens/Home/HomeScreen.js
  src/presentation/screens/Profile/AnonymousProfileScreen.js
  src/presentation/screens/Profile/ProfileScreen.js
  src/presentation/screens/Register/RegisterStepTwo/RegisterStepTwoScreen.js
  src/presentation/screens/Search/SearchScreen.js
  src/presentation/screens/TermsCondition/TermsCondition.js
Labels: enhancement

#176 T-174 Update the Google API and use it in Mapascreen
  app.json
  src/presentation/components/Search/Search.js
  src/presentation/screens/Favorites/FavoritesScreen.js
  src/presentation/screens/Map/MapaScreen.js
  src/presentation/screens/ProfileInformation/ProfileInformationScreen.js
  src/presentation/screens/Search/SearchScreen.js
  src/services/places.js
  src/shared/assets/pin.png
Labels: enhancement

#179 T-138 Integration Backend Reviews By Places Screen and Add Review
  src/data/datasources/reviews/reviewsDataSource.js
  src/data/repositories/reviews/reviewsRepository.js
  src/data/repositories/reviews/reviwsRepository.js
  src/domain/models/reviews/reviews.js
  src/domain/usecases/reviews/getReviewsByPlaceIdUseCase.js
  src/infrastructure/api/reviews/reviewApi.js
  src/infrastructure/api/reviews/reviewsApi.js
  src/presentation/components/DetailInfo/DetailInfo.js
  src/presentation/components/HorizontalCardPLace/HorizontalCardPlace.js
  src/presentation/navigation/AppNavigation.js
  src/presentation/screens/Detail/DetailScreen.js
  src/presentation/screens/Home/HomeScreen.js
  src/presentation/screens/Map/MapaScreen.js
  src/presentation/screens/PlaceReviews/PlaceReviewsScreen.js
  src/presentation/screens/Profile/AnonymousProfileScreen.js
  src/presentation/screens/Search/SearchScreen.js
  src/services/places.js
Labels: enhancement

#187 T-186 Modify the Implementation to api google maps in Map
  app.json
  src/services/places.js
  src/shared/assets/pin.png
Labels: enhancement

#188 T-183 Integration of component ratign in the card of the view to review
  src/presentation/components/ReviewCard/ReviewCard.js
  src/presentation/screens/Detail/DetailScreen.js
  src/presentation/screens/PlaceReviews/PlaceReviewsScreen.js
Labels: duplicate

#189 T-185 Implementation icons of Categories
  src/presentation/navigation/AppNavigation.js
  src/presentation/screens/Categories/CategoriesScreen.js
  src/presentation/screens/Home/HomeScreen.js
Labels: duplicate

#191 T-190 Add Navegation fo component horizontal card place in to screen map
  src/presentation/components/DetailInfo/DetailInfo.js
  src/presentation/components/HorizontalCardPLace/HorizontalCardPlace.js
  src/presentation/components/VerticalPlaceCard/VerticalPlaceCard.js
  src/presentation/screens/Home/HomeScreen.js
Labels: duplicate, enhancement

#210 T-203 Implement route marking in Mapascreen
  src/presentation/screens/Map/MapaScreen.js
Labels: duplicate, enhancement

#211 T-197 Fix Section Home
  src/presentation/components/MainHeader/MainHeader.js
  src/presentation/navigation/AppNavigation.js
  src/presentation/screens/Home/HomeScreen.js
  src/presentation/screens/Notifications/NotificationsScreen.js
  src/presentation/screens/NotificationsScreen/NotificationsScreen.js
Labels: bug, duplicate

#213 T-201 Clean to Blocks of Try Catch
  src/context/LogVisitContext.js
  src/data/datasources/favorites/favoritesDataSource.js
  src/data/datasources/places/mostVisitedPlacesDataSources.js
  src/data/datasources/places/placesByCategoryDataSource.js
  src/data/datasources/placesDetail/placesDetailDataSource.js
  src/data/datasources/users/usersDataSource.js
  src/data/repositories/favorites/favoritesRepository.js
  src/data/repositories/placesDetail/placesDetailRepository.js
  src/data/repositories/tags/tagsRepository.js
  src/data/repositories/termsAndConditions/termsAndConditionsRepository.js
  src/data/repositories/users/usersRepository.js
  src/domain/models/placesDetail/placesDetail.js
  src/domain/models/reviews/reviews.js
  src/domain/usecases/favorites/addFavoriteUseCase.js
  src/domain/usecases/favorites/deleteFavoriteUseCase.js
  src/domain/usecases/favorites/getFavoritesUseCase.js
  src/domain/usecases/places/getPlacesByCategoryUseCase.js
  src/domain/usecases/placesDetail/getPlaceDetailUseCase.js
  src/domain/usecases/tags/getDefaultTagsUseCase.js
  src/domain/usecases/termsAndConditions/getTermsAndConditionsUrlUseCase.js
  src/domain/usecases/user/changePasswordUseCase.js
  src/infrastructure/api/categories/categoriesApi.js
  src/infrastructure/api/favorites/favoritesApi.js
  src/infrastructure/api/logVisit/logVisitApi.js
  src/infrastructure/api/places/placesApi.js
  src/infrastructure/api/placesDetail/placesDetailApi.js
  src/infrastructure/api/reviews/reviewsApi.js
  src/infrastructure/api/tags/tagsApi.js
  src/infrastructure/api/termsAndConditions/termsAndConditionsApi.js
  src/infrastructure/api/users/usersApi.js
  src/infrastructure/services/httpClientService.js
  src/infrastructure/storage/.txt
  src/infrastructure/storage/userStorage.js
  src/presentation/components/CustomInput/CustomInputText.js
  src/presentation/components/NavigationTopBar/NavigationTopBar.js
  src/presentation/components/VerticalPlaceCard/VerticalPlaceCard.js
  src/presentation/hooks/places/useMostVisitedPlaces.js
  src/presentation/hooks/places/useTopRatedPlacesByCategory.js
  src/presentation/screens/Categories/CategoriesScreen.js
  src/presentation/screens/Detail/DetailScreen.js
  src/presentation/screens/Favorites/FavoritesScreen.js
  src/presentation/screens/Login/LoginScreen.js
  src/presentation/screens/Map/MapaScreen.js
  src/presentation/screens/PasswordRecovery/PasswordRecoveryStepOneScreen.js
  src/presentation/screens/PasswordRecovery/PasswordRecoveryStepThreeScreen.js
  src/presentation/screens/PasswordRecovery/PasswordRecoveryStepTwoScreen.js
  src/presentation/screens/PlaceReviews/PlaceReviewsScreen.js
  src/presentation/screens/Profile/ProfileScreen.js
  src/presentation/screens/ProfileInformation/ProfileInformationScreen.js
  src/presentation/screens/Register/RegisterStepOne/RegisterStepOneScreen.js
  src/presentation/screens/Register/RegisterStepTwo/RegisterStepTwoScreen.js
  src/presentation/screens/Search/SearchScreen.js
  src/presentation/screens/TermsCondition/TermsCondition.js
  src/services/places.js
  src/shared/context/LogVisitContext.js
  src/shared/store/favoritesSlice/favoritesSlice.js
Labels: bug, duplicate

#215 add middleware to management panel with eamil of coofundation
  src/presentation/screens/Profile/ProfileScreen.js
Labels: enhancement, help wanted
